development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  database: list_to_dec
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  database: list_to_dec
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  database: list_to_dec
  timeout: 5000